### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
Getting this error for Python 2.7 and Numpy 1.16.5 on Windows:

```
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    import numpy as np
  File "C:\Miniconda-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Miniconda-x64\lib\site-packages\numpy\core\__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Miniconda-x64\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log
     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.
Original error was: DLL load failed: The specified module could not be found.
```

**Comment by moorepants** [comment]
Also getting this with Python 3.6.10 and NumPy1.16.5:

```
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
python --version
Python 3.6.10
python -c "import struct; print(struct.calcsize('P') * 8)"
64
python setup.py install
Traceback (most recent call last):
  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray
  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides
  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    import numpy as np
  File "C:\Miniconda36-x64\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Miniconda36-x64\lib\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.6 from "C:\Miniconda36-x64\python.exe"
  * The NumPy version is: "1.18.4"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: DLL load failed: The specified module could not be found.
Command exited with code 1
```

**Comment by moorepants** [comment]
Hah, i had this issue before: https://github.com/numpy/numpy/issues/15003

**Comment by apommel** [comment]
I solved it in my PR. I should probably have made a separate one for this. You need to add `- "CALL %PYTHON%\\Scripts\\activate.bat base"` in `appveyor.yml` before calling conda.

**Comment by apommel** [comment]
conda is always a bit tricky with its activation, especially on Windows. I don't think it will break for something related anymore this way though.

**Comment by moorepants** [comment]
> I can't seem to add it directly with te review tool, but maybe the environment variable IPOPTWINDIR in setup.py could be renamed IPOPT_DIR as it is a more standard name for an environment variable.

I think I specifically didn't use IPOPT_DIR for some reason, but can't quite recall. This would be backwards incompatible, so I'll leave it for this release.

**Pull request merged**
