### PR TITLE
Patch environment variable for ipopt conda forge

### PR DESCRIPTION
**Pull request by ashander**
Attempted fix to #78

### CODE REVIEW

**Comment by ashander** [comment]
- oops I completely broke 2.7 so it doesn't have ipopt at all
- for the others, I think before #78 can work there is an issue upstream with conda forge ipopt. Downloading windows build from https://github.com/coin-or/Ipopt/releases includes DLLs that are nowhere in the conda prefix (eg `ipopt.dll.lib` which these appveyor 3.x builds choked on and `ipopt-3.dll` which my local install broke on)

**Comment by brocksam** [comment]
I've got a PR in the works for a version 1.0.0 release proposal (#75). I think the consensus was to drop Python 2.7 support if there is a 1.0.0 release so if conda-forge IPOPT is Python 3.x only then those two could be tied in together...

**Comment by ashander** [comment]
Thanks @brocksam dropping 2.7 probably makes sense, although I'm not sure conda-forge is intended to be 3.x only. I'll let @moorepants weigh in.

I think the deeper issue is these DLLs. Reading through the issues and PRs https://github.com/conda-forge/ipopt-feedstock/issues/1 https://github.com/conda-forge/ipopt-feedstock/pull/47 that implemented windows build of ipopt on conda-forge, I can't tell if this lack of DLLs is intended behavior. For example see [this comment](https://github.com/conda-forge/ipopt-feedstock/issues/1#issuecomment-652381352) at the end of windows issue 1 referring to static libs vs dynamic. If it is intended then does cyipopt need to compile against different libs in setup.py? I'm out of depth so mostly just reporting that the current setup of ipopt from conda-forge do not have these DLLs anywhere and so will not work the way the windows builds from coin-or have.

**Comment by moorepants** [comment]
> I think the consensus was to drop Python 2.7 support if there is a 1.0.0 release so if conda-forge IPOPT is Python 3.x only then those two could be tied in together...

Yes, let's drop 2.7 in that PR. Should I make one more release 0.2.1 for PR #63 and maybe this PR?

**Comment by moorepants** [comment]
The ipopt-feedstock should be compiled as dynamic libraries, not static. I think conda-forge wants all libs dynamic.

**Comment by brocksam** [comment]
> Yes, let's drop 2.7 in that PR. Should I make one more release 0.2.1 for PR #63 and maybe this PR?

Yep, if there was a release containing PR #63 and this one then I can update PR #75 so that it universally supports all OSs with IPOPT 13.3 and that'd result in a clean cross-platform solution in 1.0.0 and beyond.

**Comment by moorepants** [comment]
Closing in favor of #78

**Pull request closed without merging**
