### PR TITLE
Makes SciPy Optional. Fixes #7.

### LINKED ISSUE #7: Make scipy optional
I think it would be nice if scipy was an optional dependency as it was before this fork occurred.

### PR DESCRIPTION
**Pull request by moorepants**
#10 should be merged first.

### CODE REVIEW

**Comment by matthias-k** [comment]
@moorepants This PR is conflicting now.

**Comment by matthias-k** [comment]
@moorepants The test fails since `python -c "import ipopt"` requires scipy. To make it optional, it probably is easiest to move all scipy imports inside the functions which need them. Although not even `minimize_ipopt` will run without scipy (since the optimization result is imported from scipy).

**Comment by moorepants** [comment]
I was under the incorrect impression that pre-fork this package did not require scipy. But it seems that the coo_matrix is used in cyipopt.pyx on one line. Maybe i should just abandon the idea to make scipy optional especially since you've add new functionality that depends on scipy.

**Comment by moorepants** [comment]
Turns out that coo_matrix wasn't needed. This works now. Let me know what you think.

**Comment by moorepants** [comment]
Is this acceptable now? If the user tries to use the class or function in ipopt_wrapper.py and scipy is not installed they get an ImportError with a custom message.

**Comment by moorepants** [comment]
Gonna merge, isn't fundamentally changing functionality, just doesn't crap out on `import ipopt` if scipy isn't installed.

**Pull request merged**
